import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiCodeforces,
  SiGeeksforgeeks,
  SiLeetcode,
  SiPython,
  SiCplusplus,
  SiDart,
  SiFlutter,
  SiAndroid,
  SiFastapi,
  SiPostgresql,
  SiMysql,
  SiOpenai,
  SiTensorflow,
  SiDocker,
  SiGit,
  SiLinux,
  SiGoogle,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaAws,
  FaDatabase,
  FaCube,
  FaSitemap,
  FaCode,
  FaPlug,
  FaBrain,
  FaExpand,
  FaLanguage,
  FaLock,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  codolio: SiCodeforces,
  geeksforgeeks: SiGeeksforgeeks,
  leetcode: SiLeetcode,
  python: SiPython,
  cplusplus: SiCplusplus,
  dart: SiDart,
  sql: FaDatabase,
  flutter: SiFlutter,
  android: SiAndroid,
  bloc: FaCube,
  cleanarch: FaSitemap,
  api: FaCode,
  fastapi: SiFastapi,
  websockets: FaPlug,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  openai: SiOpenai,
  rag: FaBrain,
  vectordb: FaDatabase,
  tensorflow: SiTensorflow,
  ocr: FaExpand,
  nlp: FaLanguage,
  docker: SiDocker,
  aws: FaAws,
  awsiam: FaLock,
  git: SiGit,
  linux: SiLinux,
  mlkit: SiGoogle,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
